# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: linkhalde
email: martin.knudsen@linkhal.de
description: >- # this means to ignore newlines until "baseurl:"
 a collection of links, a linkhalde.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://linkhal.de" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: theknudsen
github_username: mknudsen
linkedin_username: dermartinknudsen
youtube_username: jerryfletcher
instagram_username: martin.kndsn
#google_analytics: UA-12320242-1
# Build settings
markdown: kramdown
theme: minima

tag_page_layout: tag_page
tag_page_dir: tag

header_pages:
  - about.md
  - impressum.html
  - contact.md
  - tools/index.md
  - gaming/index.md
  - finance/index.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo
  - jekyll/tagging
  - jekyll-include-cache

paginate: 25
paginate_path: "/blog/page/:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - import-goodreads.sh
   - import-letterboxd.sh
