# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Workflow for building and deploying a Jekyll site to Netcup
name: Deploy Jekyll site to Netcup

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Schedule the workflow to run every day at 04:00 UTC (06:00 CEST)
  schedule:
    - cron: '0 4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "netcup-deployment"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Devbox
        uses: jetify-com/devbox-install-action@v0.14.0
        with:
          enable-cache: true
      - name: Install dependencies
        run: devbox run -- bundle install
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: devbox run -- bundle exec jekyll build && ls ./_site
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site/

  # Netcup deployment job
  deploy-netcup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Jekyll artifact
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: _site/
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.NETCUP_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.NETCUP_HOSTNAME }} >> ~/.ssh/known_hosts
      - name: Set permissions before deployment
        run: |
          chmod -R u=rwX,go=rX _site/
      - name: Deploy with rsync
        run: |
          rsync -rzv _site/ ${{ secrets.NETCUP_USER }}@${{ secrets.NETCUP_HOSTNAME }}:/linkhal.de/httpdocs/
